services:
  Apps.mooc.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.mooc.controllers.CoursePutController:
    class: ../../controllers/CoursePutController
    arguments: ['@Mooc.Courses.application.CoursesCreator']

  Apps.mooc.controllers.UserPutController:
    class: ../../controllers/UserPutController
    arguments: ['@Mooc.Users.application.UserCreator']
