services:
  Mooc.MongoConfig:
    factory:
      class: '../../../../../Contexts/Mooc/Shared/infraestructure/persistence/mongo/MongoConfigFactory'
      method: createConfig

  Mooc.ConnectionManager:
    factory:
      class: '../../../../../Contexts/Shared/infrasestructure/persistence/mongo/MongoClientFactory'
      method: 'createClient'
    arguments: ['mooc', '@Mooc.MongoConfig']

  Mooc.Courses.application.CoursesCreator:
    class: ../../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: ['@Mooc.Courses.domain.CourseRepository']

  Mooc.Courses.domain.CourseRepository:
    class: ../../../../../Contexts/Mooc/Courses/infraestructure/persistence/FileCourseRepository
    arguments: ['']
